language: 
  - cpp 
compiler:
  - clang
install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev 
s
  - sudo apt-get install cmake libboost-dev
before_script:
  - git clone https://github.com/audiofilter/spuc.git
  - mkdir build
  - cd build
  - cmake ..
script: make
