os:
  - osx
language: 
  - objective-c
compiler:
  - clang
before_install:
  - brew update
	- brew tap audiofilter/spuc
install:
  - brew install qt5
  - brew linkapps
	- brew install spuc
# Change this to your needs
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
