language: 
  - c
compiler:
  - clang
install:
  - sudo apt-get install cmake boost qt5
before_script:
  - git clone https://github.com/audiofilter/spuc.git
  - mkdir build
  - cd build
  - cmake ..
script: make
